# Generated by Django 2.2.5 on 2019-10-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_declaracaodesaude_pontuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracaodesaude',
            name='outradoenca',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='declaracaodesaude',
            name='outradoencadetalhes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descreva aqui'),
        ),
    ]
