# Generated by Django 2.2.5 on 2019-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20190917_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans27',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans28',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
