# Generated by Django 2.2.5 on 2019-09-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
