# Generated by Django 2.2.5 on 2019-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20190918_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans27',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans28',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
