# Generated by Django 2.2.5 on 2019-09-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20190918_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='declaracaodesaude',
            name='ans27',
        ),
        migrations.RemoveField(
            model_name='declaracaodesaude',
            name='ans28',
        ),
        migrations.AddField(
            model_name='declaracaodesaude',
            name='ans19detalhes',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracaodesaude',
            name='ans20detalhes',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracaodesaude',
            name='ans21detalhes',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracaodesaude',
            name='ans22detalhes',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='declaracaodesaude',
            name='ans23detalhes',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans25',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans26',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
