# Generated by Django 2.2.5 on 2019-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20190918_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans19detalhes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descreva aqui'),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans20detalhes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descreva aqui'),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans21detalhes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descreva aqui'),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans22detalhes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descreva aqui'),
        ),
        migrations.AlterField(
            model_name='declaracaodesaude',
            name='ans23detalhes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descreva aqui'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
    ]
