# Generated by Django 2.2.6 on 2019-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20191016_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, default=0, max_length=15),
            preserve_default=False,
        ),
    ]
