# Generated by Django 2.2.6 on 2019-10-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_auto_20191016_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=0, verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_inclusao',
            field=models.DateField(default=0, verbose_name='Data de inclusão no plano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('cpf', 'birth_date', 'sexo')},
        ),
    ]
