# Generated by Django 2.2.5 on 2019-09-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acirsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datareg', models.PositiveSmallIntegerField()),
                ('coracao', models.PositiveSmallIntegerField()),
                ('vascular', models.PositiveSmallIntegerField()),
                ('hematopoietico', models.PositiveSmallIntegerField()),
                ('respiratorio', models.PositiveSmallIntegerField()),
                ('otorrino', models.PositiveSmallIntegerField()),
                ('gastrointestinalsup', models.PositiveSmallIntegerField()),
                ('gastrointestinalinf', models.PositiveSmallIntegerField()),
                ('figado', models.PositiveSmallIntegerField()),
                ('renal', models.PositiveSmallIntegerField()),
                ('genitourinario', models.PositiveSmallIntegerField()),
                ('neurologico', models.PositiveSmallIntegerField()),
                ('endocrino', models.PositiveSmallIntegerField()),
                ('psiquiatrica', models.PositiveSmallIntegerField()),
                ('numcatclass', models.PositiveSmallIntegerField()),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('indgravidade', models.PositiveSmallIntegerField()),
                ('numcatsev3', models.PositiveSmallIntegerField()),
                ('numcatsev4', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
