# Generated by Django 2.2.5 on 2019-10-03 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import escalas.funcoes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalasocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('medico_id', models.IntegerField(verbose_name='Médico ID')),
                ('datareg', models.DateTimeField(auto_now_add=True)),
                ('acamado', models.BooleanField()),
                ('deficienciafisica', models.BooleanField(verbose_name='Deficiência Física')),
                ('deficienciamental', models.BooleanField(verbose_name='Deficiência Mental')),
                ('saneamento', models.BooleanField(verbose_name='Saneamento precário')),
                ('desnutricao', models.BooleanField(verbose_name='Desnutrição(grave)')),
                ('drogadicao', models.BooleanField(verbose_name='Drogadição')),
                ('desempregado', models.BooleanField(verbose_name='Desempregado')),
                ('analfabetismo', models.BooleanField(verbose_name='Analfabetismo')),
                ('menor', models.BooleanField(verbose_name='Menor de 6 meses')),
                ('maior', models.BooleanField(verbose_name='Maior de 70 anos')),
                ('hipertensao', models.BooleanField(verbose_name='Hipertensão A. S.')),
                ('moradores', models.PositiveSmallIntegerField(verbose_name='Número de moradores por cômodo')),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('totalemrisco', models.PositiveSmallIntegerField()),
                ('totalforaderisco', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escalamedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('medico_id', models.IntegerField(verbose_name='Médico ID')),
                ('datareg', models.DateTimeField(auto_now_add=True)),
                ('coracao', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('vascular', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('hematopoietico', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('respiratorio', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('otorrino', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('gastrointestinalsup', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('gastrointestinalinf', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('figado', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('renal', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('genitourinario', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('musculosqueletico', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('neurologico', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('endocrino', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('psiquiatrica', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('numcatclass', models.PositiveSmallIntegerField()),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('indgravidade', models.FloatField()),
                ('numcatsev0', models.PositiveSmallIntegerField()),
                ('numcatsev1', models.PositiveSmallIntegerField()),
                ('numcatsev2', models.PositiveSmallIntegerField()),
                ('numcatsev3', models.PositiveSmallIntegerField()),
                ('numcatsev4', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Escalaenfermagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('medico_id', models.IntegerField(verbose_name='Médico ID')),
                ('datareg', models.DateTimeField(auto_now_add=True)),
                ('estadomental', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('oxigenacao', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('sinaisvitais', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('motibilidade', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('deambulacao', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('alimentacao', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('cuidadocorporal', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('eliminacao', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('terapeutica', models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4])),
                ('soma1', models.PositiveSmallIntegerField()),
                ('soma2', models.PositiveSmallIntegerField()),
                ('soma3', models.PositiveSmallIntegerField()),
                ('soma4', models.PositiveSmallIntegerField()),
                ('somatotal', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
