# Generated by Django 2.2.6 on 2019-10-16 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalafisioterapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Fisioterapeuta')),
                ('medico_id', models.IntegerField(verbose_name='Médico ID')),
                ('datareg', models.DateTimeField(auto_now_add=True)),
                ('banho', models.BooleanField(verbose_name='Banho')),
                ('vestir', models.BooleanField(verbose_name='Vertir-se')),
                ('higiene', models.BooleanField(verbose_name='Higiene')),
                ('transferencia', models.BooleanField(verbose_name='Transferência')),
                ('continencia', models.BooleanField(verbose_name='Continência')),
                ('alimentacao', models.BooleanField(verbose_name='Alimentação')),
                ('niveldor', models.PositiveSmallIntegerField(default=1, verbose_name='Nível de dor')),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
