# Generated by Django 2.2.5 on 2019-09-28 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escalas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalamedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('medico_id', models.IntegerField(max_length=150, verbose_name='Médico')),
                ('datareg', models.PositiveSmallIntegerField()),
                ('coracao', models.PositiveSmallIntegerField()),
                ('vascular', models.PositiveSmallIntegerField()),
                ('hematopoietico', models.PositiveSmallIntegerField()),
                ('respiratorio', models.PositiveSmallIntegerField()),
                ('otorrino', models.PositiveSmallIntegerField()),
                ('gastrointestinalsup', models.PositiveSmallIntegerField()),
                ('gastrointestinalinf', models.PositiveSmallIntegerField()),
                ('figado', models.PositiveSmallIntegerField()),
                ('renal', models.PositiveSmallIntegerField()),
                ('genitourinario', models.PositiveSmallIntegerField()),
                ('neurologico', models.PositiveSmallIntegerField()),
                ('endocrino', models.PositiveSmallIntegerField()),
                ('psiquiatrica', models.PositiveSmallIntegerField()),
                ('numcatclass', models.PositiveSmallIntegerField()),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('indgravidade', models.PositiveSmallIntegerField()),
                ('numcatsev3', models.PositiveSmallIntegerField()),
                ('numcatsev4', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Acirsg',
        ),
    ]
