# Generated by Django 2.2.5 on 2019-09-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_auto_20190928_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalamedica',
            name='datareg',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='medico_id',
            field=models.IntegerField(verbose_name='Médico ID'),
        ),
    ]
