# Generated by Django 2.2.5 on 2019-09-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0003_auto_20190928_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalamedica',
            name='musculosqueletico',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
