# Generated by Django 2.2.5 on 2019-09-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0004_escalamedica_musculosqueletico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalamedica',
            name='indgravidade',
            field=models.FloatField(),
        ),
    ]
