# Generated by Django 2.2.5 on 2019-09-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0005_auto_20190928_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalamedica',
            name='numcatsev0',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalamedica',
            name='numcatsev1',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalamedica',
            name='numcatsev2',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
