# Generated by Django 2.2.5 on 2019-09-30 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import escalas.funcoes


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escalas', '0006_auto_20190929_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalamedica',
            name='coracao',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='endocrino',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='figado',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='gastrointestinalinf',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='gastrointestinalsup',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='genitourinario',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='hematopoietico',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='musculosqueletico',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='neurologico',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='otorrino',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='psiquiatrica',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='renal',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='respiratorio',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalamedica',
            name='vascular',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.CreateModel(
            name='Escalasocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('medico_id', models.IntegerField(verbose_name='Médico ID')),
                ('datareg', models.DateTimeField(auto_now_add=True)),
                ('acamado', models.BooleanField()),
                ('deficienciafisica', models.BooleanField()),
                ('deficienciamental', models.BooleanField()),
                ('saneamento', models.BooleanField()),
                ('desnutricao', models.BooleanField()),
                ('drogadicao', models.BooleanField()),
                ('desempregado', models.BooleanField()),
                ('analfabetismo', models.BooleanField()),
                ('menor', models.BooleanField()),
                ('maior', models.BooleanField()),
                ('hipertensao', models.BooleanField()),
                ('moradores', models.PositiveSmallIntegerField()),
                ('pontuacao', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
