# Generated by Django 2.2.5 on 2019-10-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0007_auto_20190930_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalasocial',
            name='totalareasemrisco',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalasocial',
            name='totalforaderisco',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='deficienciafisica',
            field=models.BooleanField(verbose_name='Deficiência Física'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='deficienciamental',
            field=models.BooleanField(verbose_name='Deficiência Mental'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='desnutricao',
            field=models.BooleanField(verbose_name='Desnutrição'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='drogadicao',
            field=models.BooleanField(verbose_name='Drogadição'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='hipertensao',
            field=models.BooleanField(verbose_name='Hipertensão'),
        ),
    ]
