# Generated by Django 2.2.5 on 2019-10-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0008_auto_20191001_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escalasocial',
            old_name='totalareasemrisco',
            new_name='totalemrisco',
        ),
    ]
