# Generated by Django 2.2.5 on 2019-10-02 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escalas', '0009_auto_20191001_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalasocial',
            name='analfabetismo',
            field=models.BooleanField(verbose_name='Analfabetismo'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='desempregado',
            field=models.BooleanField(verbose_name='Desempregado'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='desnutricao',
            field=models.BooleanField(verbose_name='Desnutrição(grave)'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='hipertensao',
            field=models.BooleanField(verbose_name='Hipertensão A. S.'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='maior',
            field=models.BooleanField(verbose_name='Maior de 70 anos'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='menor',
            field=models.BooleanField(verbose_name='Menor de 6 meses'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='moradores',
            field=models.PositiveSmallIntegerField(verbose_name='Número de moradores por cômodo'),
        ),
        migrations.AlterField(
            model_name='escalasocial',
            name='saneamento',
            field=models.BooleanField(verbose_name='Saneamento precário'),
        ),
        migrations.CreateModel(
            name='Escalaenfermagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=150, verbose_name='Médico')),
                ('medico_id', models.IntegerField(verbose_name='Médico ID')),
                ('datareg', models.DateTimeField(auto_now_add=True)),
                ('estadomental', models.PositiveSmallIntegerField()),
                ('oxigenacao', models.PositiveSmallIntegerField()),
                ('sinaisvitais', models.PositiveSmallIntegerField()),
                ('motibilidade', models.PositiveSmallIntegerField()),
                ('deambulacao', models.PositiveSmallIntegerField()),
                ('alimentacao', models.PositiveSmallIntegerField()),
                ('cuidadocorporal', models.PositiveSmallIntegerField()),
                ('eliminacao', models.PositiveSmallIntegerField()),
                ('terapeutica', models.PositiveSmallIntegerField()),
                ('soma1', models.PositiveSmallIntegerField()),
                ('soma2', models.PositiveSmallIntegerField()),
                ('soma3', models.PositiveSmallIntegerField()),
                ('soma4', models.PositiveSmallIntegerField()),
                ('somatotal', models.PositiveSmallIntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
