# Generated by Django 2.2.5 on 2019-10-02 17:27

from django.db import migrations, models
import escalas.funcoes


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0010_auto_20191002_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='alimentacao',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='cuidadocorporal',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='deambulacao',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='eliminacao',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='estadomental',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='motibilidade',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='oxigenacao',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='sinaisvitais',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
        migrations.AlterField(
            model_name='escalaenfermagem',
            name='terapeutica',
            field=models.PositiveSmallIntegerField(validators=[escalas.funcoes.valida0entre4]),
        ),
    ]
